### ISSUE TITLE
Unfortunately, Modulz repo is not a tool but "An open-source UI component library" and it was acquired recently 

### ISSUE THREAD

**Issue by diacritica** [RunaCapital/awesome-oss-alternatives#136]
Hi! I love what you guys are doing at RunaCapital, it helps drive awareness towards great OSS tools. I'm in the design space so I'm curious about anything relevant on that field (other than Penpot, of course). Modulz is listed as an alternative to Figma but the repo you link is about open UI components, sort of a designers toolkit, but not a tool. Their tool would be this one https://www.modulz.app/ but it has never released any alpha or beta and very recently they announced they had been acquired by WorkOS https://www.modulz.app/blog/modulz-acquired-by-workos. It doesn't look very good for the future of that tool.
I would suggest you change the description for Modulz. Do you need a specific pull-request or will you do it yourselves?

**Comment by garrrikkotua** [comment]
hey @diacritica 

Thanks a lot for highlighting this! PR is always welcome :)

Regarding other OSS design tools, you might be interested to take a look at https://webstudio.is/ (aka alternative to WebFlow). It is not in the list yet, I will add it soon :)

**Comment by diacritica** [comment]
Hi Igor!

Sounds great! We know plasmiq, which could be seen as an OSS alternative to
webflow (we use it for that purpose). I will take a look at webstudio.is,
thanks!
Shall I send a PR changing the Modulz listing then?

Best!
Pablo

**Comment by garrrikkotua** [comment]
yep, feel free to send a PR :)
