### ISSUE TITLE
Many of the listed projects/start-up are not Open Source

### ISSUE THREAD

**Issue by ssddanbrown** [RunaCapital/awesome-oss-alternatives#143]
Hi! Just had a scan through the project list and noticed many of these are generally not considered to be "Open Source" as per the [common definition](https://opensource.org/osd). 

- FusionAuth - Can't find any significant open source offering.
- Tracardi - Applies commons clause.
- Chaskiq - Applies commons clause.
- Gravitl (netmaker) - SSPL License.
- Lunatrace - Very mixed, Large portions BSL (Including lunatrace portion)
- Airbyte - Defaults to Elastic License 2.
- Memgraph - Mixed BSL and custom enterprise.
- Graylog - SSPL.
- Outline - BSL.
- Sentry - BSL.
- Uptrace - BSL.
- Castled - Can't find any significant open source offering.
- OpenReplay - Elastic License 2.
- N8N - Sustainable Use License.

I think all the BSL licenses were backed by Open Source licenses, making them a bit of a grey area, but in many cases, applying your 10-year start-up window, it does mean that the source be be non-Open-Source for half that 10 year time, then somewhat outdated for the remainder.

**Comment by ssddanbrown** [comment]
Would a PR be accepted to remove the listed items?

**Comment by garrrikkotua** [comment]
Hey @ssddanbrown!

I agree that FusionAuth and Castled should be removed, but regarding others I don't really want to do this, because for many people it still super usefull to know about these tools (even if they source avalialbe VS completely open-source).

So I am happy to accept PR removing FusionAuth and Castled.

**Comment by garrrikkotua** [comment]
On the other hand, it would be super cool to add a license column to the table - I think many people would benefit from that. 

It's quite a lot of work, so I would be super happy if someone wants to collaborate on this 😄

**Comment by ssddanbrown** [comment]
Hi @garrrikkotua,

> On the other hand, it would be super cool to add a license column to the table - I think many people would benefit from that.

That sounds like a good improvement.

> I don't really want to do this, because for many people it still super usefull to know about these tools (even if they source avalialbe VS completely open-source).

Okay, but are you looking to still keep the list name, description and criteria the same, with references to "Open Source" specifically?

I ask because many folks that love and work in Open Source, including myself, get concerned when seeing attempts to stretch the term "Open Source" outside of the common OSI definition, commonly for marketing benefit of the projects doing so.
This counters the efforts that have been made to build the reputation of Open Source, and in my opinion these licenses counter what Open Source is about by putting the freedoms/interests of their business first over the code/users. 
I don't think there's anything specifically wrong with that though, or that I think it's wrong for people to protect their business or livelihoods, it's just the particular case of applying "Open Source" to such projects/license.
I'd worry that including such "source available" projects along with the "Open Source" terminology would only enforce that idea that open source means "open to viewing" rather than being fully "open to viewing, use and distribution without discrimination".

**Comment by ErvinSmit** [comment]
When you start a startup, it's always difficult to sort out and start working without mistakes. But I believe that at least it's worth using digital technologies right away, so that later you don’t bother with the transition to them.

**Comment by micucarachacha** [comment]
I agree with you because technology helps optimize business and that makes a lot of sense because it's impossible to expand a business if there are various optimization issues. In general, I always support the digital transition, including [saas in cloud migration](https://apiko.com/blog/traditional-app-migration-to-saas-2/). I think that you should read more about this, cause this is really something that will help you immediately choose the right path in doing business.
