### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [RunaCapital/awesome-oss-alternatives#166]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by DerAlbertCom** [comment]
https://github.com/RunaCapital/awesome-oss-alternatives/pulls?q=is%3Apr+is%3Aclose

**Comment by Firefoxy2026** [comment]
yes

**Comment by Firefoxy2026** [comment]
anyone wanna zoom
