### ISSUE TITLE
May be Pipedream can also be added to the list

### ISSUE THREAD

**Issue by ekansh005** [RunaCapital/awesome-oss-alternatives#23]
Hi,

I find pipedream (https://github.com/PipedreamHQ/pipedream) quite interesting and have used it couple of times. May be this can be added to the list.

**Comment by ekansh005** [comment]
I think it can be categorized as alternative to Zapeir for that matter. @dylburger can provide his opinion.

**Comment by dylburger** [comment]
Thanks @ekansh005 ! Yes, Zapier and Integromat are good comparisons. Pipedream is like Zapier for developers.

**Comment by garrrikkotua** [comment]
Added, thank you!
