### ISSUE TITLE
Add `GoatCounter` to the website analytics section

### ISSUE THREAD

**Issue by cipriancraciun** [RunaCapital/awesome-oss-alternatives#24]
GoatCounter is another alternative to Google Analytics, also I think it meets the desired requirements:
* it is open source <https://github.com/arp242/goatcounter> with +2.3K stars;
* it is also a company <https://www.goatcounter.com/>;

I assume @arp242 (the author of GoatCounter) can provide furter details if needed.

**Comment by garrrikkotua** [comment]
@cipriancraciun sure, happy to add it!

Would you like to make a PR?

**Comment by cipriancraciun** [comment]
I've looked at how to contribute, and it's a bit "involved" for a one-line pull contribution.

However, I can provide all the information in this issue, and I guess (since you already have the repository) it'll be simplest for everyone.  :)

~~~~
Website analytics|[GoatCounter](https://www.goatcounter.com/)|Google Analytics alternative|<a href=https://github.com/arp242/goatcounter><img src="https://img.shields.io/github/stars/arp242/goatcounter?style=social" width=150/></a>|[Google Analytics](https://analytics.google.com/)
~~~~

----

Might I make a few suggestions to improve the whole process:

* given my above line, I actually see that you require only a few pieces of information:
  * a category, which you could predefine, and have the user choose from a list;
  * the company name;
  * the company URL;
  * the repository URL;
* for each company, have a TOML (or YAML, JSON, or even a plain-text) file with these four keys (and the optional description if you like);
* have a Python script that can just compile the README based on these;

You could amend the contribution request to include (as an alternative to an actual pull request) a simple issue which provides the contents of this file, so then you (or someone else) can just copy-paste them in a new file, and run the required scripts.

For example (a simple INI-like format):
~~~~
company_name = GoatCounter
company_url = https://www.goatcounter.com/
repository_url = https://github.com/arp242/goatcounter
category = web-analytics
~~~~

**Comment by garrrikkotua** [comment]
@cipriancraciun 
Thanks for your suggestion! I will add GoatCounter right away )

Yes, I am thinking of the way to make contributing easier. Right now a have CLI Python utility, which takes infomation from user and creates a new entry. But YAML is an interesting idea :)

Do you think it is possible to create some tool using GitHub Pages and GitHub Actions which would take information from the user and than create a submission / PR (perhaps on my behalf or on a user's behalf)? What would be the best solution :)

**Comment by faysou** [comment]
Modifying the markdown file is quite easy as well, not sure python is needed for just one line contribution, although it would have been useful for several contributions.

**Comment by cipriancraciun** [comment]
> Do you think it is possible to create some tool using GitHub Pages and GitHub Actions which would take information from the user and than create a submission / PR (perhaps on my behalf or on a user's behalf)? What would be the best solution :)

@garrrikkotua I don't think that's (easily) possible, but I think you can create a new issue template that has the snippet, and thus the user only needs to fill it out.

Alternatively you could create a Google Form to get the input.

----

@faysou the problem with the current Markdown file is that's quite unreadable, and modifying it can easily lead to mistakes;  moreover half of it is just duplicated (see the link for repo, link for stars, etc.)

That is why I've suggested having different formats for different purposes:
* have a simple text-based format for the actual data, which would be the "authoritative database";  I've proposed JSON/YAML/TOML because they can be easily interpreted from within Python, alternatively an INI-like format also works;
* have the Markdown only for presentation purposes on GitHub;
* perhaps generate an HTML with cards to be exposed via GitHub pages or similar;

Having each submission in it's own file also reduces the conflict during PR.
