### ISSUE TITLE
Add Vikunja

### ISSUE THREAD

**Issue by kolaente** [RunaCapital/awesome-oss-alternatives#40]
Hi, founder of Vikunja here.

Vikunja is a project management / to-do list application, replacing tools like trello, todoist, asana, etc. We have a for-profit SaaS version available called [Vikunja Cloud](https://vikunja.cloud).

I would love to add the project to the list, however, it does not have 100+ stars on a single repo. Main reason is probably we [don't primarily use github for code](https://kolaente.dev/vikunja/), we're only mirroring the code here. If you squint a bit, you could count the stars of the [frontend](https://github.com/go-vikunja/frontend) and [api](https://github.com/go-vikunja/api) repos as one, which would push it over the 100 stars requirement.

Just putting this up for discussion, any way to add Vikunja to the list? Or should I rather wait until we hit the 100+ stars for a single repo here on github?

**Comment by garrrikkotua** [comment]
Hi @kolaente 

API repo is almost at 100 stars, so I think it is better to wait until it reaches 100, just not to break the rules :) 

I will make a note and add it as soon as it reaches threshold

**Comment by garrrikkotua** [comment]
I will keep the issue open, so I rembemer to add it :)

And also here is the number of stars:

<a href=https://github.com/go-vikunja/api><img src="https://img.shields.io/github/stars/go-vikunja/api?style=social" width=150/></a>

**Comment by jesperordrup** [comment]
101 stars :-)

**Comment by kolaente** [comment]
> 101 stars :-)

Just put up a PR: https://github.com/RunaCapital/awesome-oss-alternatives/pull/117 :upside_down_face:
