### ISSUE TITLE
Add authorizer.dev

### ISSUE THREAD

**Issue by lakhansamani** [RunaCapital/awesome-oss-alternatives#48]
Hi,

I am the creator of [authorizer.dev](https://authorizer.dev), open-source authentication and authorization solution. It was the product of the day on product hunt and is at 194 stars as of today.

It is an open-source alternative auth0 with the following features

- Bring your database and own the user data
- Supports all SQL databases, MongoDB, ArangoDB, and more to come in future
- Uses Graphql as the technology and built using Golang.
- It supports multiple auth recipes (social media log in, basic auth, magic link login)
- Role based access management
- Secure session management
- Multiple deployment options. Also comes with a lot of one-click deployment options which takes away the pain of managing infra.

**Comment by garrrikkotua** [comment]
@lakhansamani hey there - thanks for the suggestion! 

Unfortunately, we add only startups (companies). Authorizers more looks like a pet-project (judjing by the website). 

Thanks for understanding :)
