### ISSUE TITLE
Add ERPNext as an ERP solution

### ISSUE THREAD

**Issue by creatorrr** [RunaCapital/awesome-oss-alternatives#49]
From their website:

> ERPNext is a full-featured business management solution that helps SMEs to record all their business transactions in a single system. With ERPNext, SMEs can make informed, fact-based, timely decisions to remain ahead in the competition. It serves as the backbone of a business adding strength, transparency, and control to your growing enterprise.

https://erpnext.com/

**Comment by garrrikkotua** [comment]
@creatorrr looks cool!

Would you like to make a PR for that?
