### ISSUE TITLE
Specify OSS License

### ISSUE THREAD

**Issue by horacioh** [RunaCapital/awesome-oss-alternatives#73]
Would be nice to list the actual license these services use on their software.

**Comment by garrrikkotua** [comment]
@horacioh thanks for your suggestion!

I am not sure I want add this directly to the list, because it would take a lot of space. You can easily look up a license in a project's repo.

Do you have ideas how should it look like? Just a new column with a license name?

**Comment by horacioh** [comment]
yep, just a new column :)

_
Horacio Herrera
https://horacioh.com
