### ISSUE TITLE
Recommendation for addition: Concrete CMS (Formerly Concrete5)

### ISSUE THREAD

**Issue by BloodyIron** [RunaCapital/awesome-oss-alternatives#8]
Yeah not sure why this isn't in the list, as it's really awesome : https://www.concretecms.com

Formerly Concrete5, now called Concrete CMS (due to versioning stuff). I've been using it for many years to build websites and the devs are totally awesome! IMO worth adding, and they're super invested in it being FOSS too.

**Comment by garrrikkotua** [comment]
Hey there,

Thanks for the suggestion!

Didn't know about this CMS, will add it for sure :)

**Comment by garrrikkotua** [comment]
Added, thank you!

**Comment by BloodyIron** [comment]
Yay! You're welcome! :D
