### ISSUE TITLE
take a step back, is this following awesome guidelines?

### ISSUE THREAD

**Issue by jnorthrup** [RunaCapital/awesome-oss-alternatives#90]
despite the egalitarian ethos of open source, every author who sees this is going to push a PR, and the list is growing to the degree where i have unsubscribed.  

is there a criterion for awesomeness besides competing with commercial licensed products presumably to bring in some dough by consulting and integration as an open source provider?

**Comment by garrrikkotua** [comment]
@jnorthrup thanks for openning an issue!

I am not sure I exactly understand your question, but still let me try to answer it :)

So in the list we aim to support COSS projects - commercial open-source products. Plus, combining it with a trend of open-source alternatives, I think it is quite awesome people do open-source projects and then turn them into businesses. I believe this is how the future of software should look like. 

> _is there a criterion for awesomeness besides competing with commercial licensed products presumably to bring in some dough by consulting and integration as an open source provider?_

I think the criteria is already pretty strict - we add only commercial open-source products which: 1) has a clear SaaS competitor 2) has 100+ stars on GitHub 3) founded less than 10 years ago 4) is a private company (we don't want to add GitLab, Elastic, etc - everyone already knows about them). So yes, I think fulfilling all these requirements makes a project really awesome :)

**Comment by jnorthrup** [comment]
i was reading on the awesome root site, brevity over completeness.  I'm seeing this is more like early yahoo or mozilla pages.  

cheers
